### ISSUE TITLE
Remote branch 1.2 could not be found

### ISSUE THREAD

**Issue by bryanhoganjordan** [warrenm/AHEasing#2]
Hey, 

I'm experiencing the following error:

`warning: Could not find remote branch 1.2 to clone.
fatal: Remote branch 1.2 not found in upstream origin`

<img width="794" alt="Screen Shot 2019-07-27 at 10 00 33 am" src="https://user-images.githubusercontent.com/45778666/61986836-641f6a80-b055-11e9-9793-11f515fde744.png">

It seems to have randomly popped up last night and I can't find the origin - just wondering that it isn't related to a server-side problem? 

Thanks :)

**Comment by nicmanzini** [comment]
tsss im in deep shit as well. Who has the idea to import such dependency in a production...

**Comment by warrenm** [comment]
Version 1.3.2 has now been released, and the podspec has been pushed to Cocoapods trunk.
